// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: account.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO "accounts" (
    user_id,
    balance
) VALUES (
    $1, $2
) RETURNING id, user_id, balance, created_at
`

type CreateAccountParams struct {
	UserID  pgtype.Int4
	Balance pgtype.Int8
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.UserID, arg.Balance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const creditAccount = `-- name: CreditAccount :one
UPDATE "accounts" SET balance = balance + $1 WHERE id = $2 RETURNING id, user_id, balance, created_at
`

type CreditAccountParams struct {
	Balance pgtype.Int8
	ID      int64
}

func (q *Queries) CreditAccount(ctx context.Context, arg CreditAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, creditAccount, arg.Balance, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const debitAccount = `-- name: DebitAccount :one
UPDATE "accounts" SET balance = balance - $1 WHERE id = $2 RETURNING id, user_id, balance, created_at
`

type DebitAccountParams struct {
	Balance pgtype.Int8
	ID      int64
}

func (q *Queries) DebitAccount(ctx context.Context, arg DebitAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, debitAccount, arg.Balance, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountById = `-- name: GetAccountById :one
SELECT id, user_id, balance, created_at FROM "accounts" WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAccountById(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountById, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const getUserAccount = `-- name: GetUserAccount :one
SELECT id, user_id, balance, created_at FROM "accounts" WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserAccount(ctx context.Context, userID pgtype.Int4) (Account, error) {
	row := q.db.QueryRow(ctx, getUserAccount, userID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}
